In [109]:
import numpy as np

arr = np.array([1,2,3,4,56,7])
arr


array([ 1,  2,  3,  4, 56,  7])

In [110]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [111]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [112]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [113]:
np.linspace(1,16,4)    ## Makes 4 equal proportion from start(1) to end(16)

array([ 1.,  6., 11., 16.])

In [114]:
arr1 = np.array([1,2,3,4,5,11])
arr2 = np.array([6,7,8,9,10,12])

np.shape(arr1)
np.reshape(arr1,(2,3))
np.concatenate([arr1,arr2,arr1])
np.vstack([arr1,arr2])  ## Arranges the array one after another
np.hstack([arr1,arr2,arr1])  ## Arrange the stack in one line

array([ 1,  2,  3,  4,  5, 11,  6,  7,  8,  9, 10, 12,  1,  2,  3,  4,  5,
       11])

In [115]:
import pandas as pd
import numpy as np
index = np.arange(15)
data1 = np.random.randint(low=1, high=20, size=15,dtype="int64")
data2 = np.random.randint(low=1, high=20, size=15,dtype="int64")
dict1 = {"data1":data1, "data2":data2}
dict1



{'data1': array([17,  6,  5,  6,  4,  6,  3,  8, 18,  5,  3,  8,  9,  3, 16]),
 'data2': array([18, 17, 14,  3, 14,  1,  2,  6,  7, 14,  7,  2, 14,  3, 12])}

In [116]:
df = pd.DataFrame(dict1, index=index)
df

,data1,data2
0,17,18
1,6,17
2,5,14
3,6,3
4,4,14
5,6,1
6,3,2
7,8,6
8,18,7
9,5,14


In [117]:
np.mean(df["data1"])
np.mean(df["data2"])

np.float64(8.933333333333334)

In [118]:
np.median(df["data2"])

np.float64(7.0)

In [119]:
np.std(df["data1"])

np.float64(4.942334131426837)

In [120]:
np.sum(df["data2"])

np.int64(134)

In [121]:
np.min(df["data2"])

np.int64(1)

In [122]:
np.max(df["data2"])

np.int64(18)

In [123]:
np.dot(df["data2"], df["data1"])

np.int64(1172)

In [124]:
print(arr1)
print(arr1[0])

[ 1  2  3  4  5 11]
1


In [125]:
print(arr1[-1])

11


In [126]:
print(arr1[1:4:2])

[2 4]


In [127]:
print(arr1[arr1>5])

[11]


# PANDAS

In [128]:
# data = { "sepal_length": [5.1, 4.9, 6.2, 5.9, 6.7, 6.5, 5.0, 6.0, 6.9, 5.5, 4.7, 5.3, 6.1, 5.6, 6.8, 7.1, 4.8, 5.7, 6.4, 6.3], "sepal_width": [3.5, 3.0, 2.9, 3.0, 3.1, 3.0, 3.4, 2.7, 3.2, 2.6, 3.2, 3.7, 2.8, 2.9, 3.0, 3.0, 3.4, 2.8, 2.8, 3.3], "petal_length": [1.4, 1.4, 4.3, 4.2, 5.6, 5.8, 1.5, 5.1, 5.7, 4.4, 1.3, 1.5, 4.0, 3.6, 5.5, 5.9, 1.6, 4.5, 5.6, 6.0], "petal_width": [0.2, 0.2, 1.3, 1.5, 2.4, 2.2, 0.2, 1.6, 2.3, 1.2, 0.2, 0.2, 1.3, 1.3, 2.1, 2.1, 0.2, 1.3, 2.2, 2.5], "species": ["setosa", "setosa", "versicolor", "versicolor", "virginica", "virginica", "setosa", "versicolor", "virginica", "versicolor", "setosa", "setosa", "versicolor", "ersicolor", "virginica", "virginica", "setosa", "versicolor", "virginica", "virginica"]}
#
# df = pd.DataFrame(data)
# df.to_csv("iris.csv")

In [129]:
df = pd.read_csv("iris.csv")
df.head()

,Unnamed: 0,sepal_length,sepal_width,petal_length,petal_width,species
0,0,5.1,3.5,1.4,0.2,setosa
1,1,4.9,3.0,1.4,0.2,setosa
2,2,6.2,2.9,4.3,1.3,versicolor
3,3,5.9,3.0,4.2,1.5,versicolor
4,4,6.7,3.1,5.6,2.4,virginica


In [130]:
df.tail()

,Unnamed: 0,sepal_length,sepal_width,petal_length,petal_width,species
15,15,7.1,3.0,5.9,2.1,virginica
16,16,4.8,3.4,1.6,0.2,setosa
17,17,5.7,2.8,4.5,1.3,versicolor
18,18,6.4,2.8,5.6,2.2,virginica
19,19,6.3,3.3,6.0,2.5,virginica


In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Unnamed: 0    20 non-null     int64  
 1   sepal_length  20 non-null     float64
 2   sepal_width   20 non-null     float64
 3   petal_length  20 non-null     float64
 4   petal_width   20 non-null     float64
 5   species       20 non-null     object 
dtypes: float64(4), int64(1), object(1)
memory usage: 1.1+ KB


In [132]:
df.shape

(20, 6)

In [133]:
df.describe()

,Unnamed: 0,sepal_length,sepal_width,petal_length,petal_width
count,20.00000,20.000000,20.000000,20.000000,20.000000
mean,9.50000,5.875000,3.065000,3.945000,1.325000
std,5.91608,0.744718,0.285205,1.806851,0.856477
min,0.00000,4.700000,2.600000,1.300000,0.200000
25%,4.75000,5.250000,2.875000,1.575000,0.200000
50%,9.50000,5.950000,3.000000,4.350000,1.300000
75%,14.25000,6.425000,3.225000,5.600000,2.125000
max,19.00000,7.100000,3.700000,6.000000,2.500000


In [134]:
df["sepal_length"]

0     5.1
1     4.9
2     6.2
3     5.9
4     6.7
5     6.5
6     5.0
7     6.0
8     6.9
9     5.5
10    4.7
11    5.3
12    6.1
13    5.6
14    6.8
15    7.1
16    4.8
17    5.7
18    6.4
19    6.3
Name: sepal_length, dtype: float64

In [135]:
df[["sepal_length","sepal_width"]]

,sepal_length,sepal_width
0,5.1,3.5
1,4.9,3.0
2,6.2,2.9
3,5.9,3.0
4,6.7,3.1
5,6.5,3.0
6,5.0,3.4
7,6.0,2.7
8,6.9,3.2
9,5.5,2.6


In [136]:
df[["sepal_length","sepal_width","petal_length","petal_width"]]

,sepal_length,sepal_width,petal_length,petal_width
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,6.2,2.9,4.3,1.3
3,5.9,3.0,4.2,1.5
4,6.7,3.1,5.6,2.4
5,6.5,3.0,5.8,2.2
6,5.0,3.4,1.5,0.2
7,6.0,2.7,5.1,1.6
8,6.9,3.2,5.7,2.3
9,5.5,2.6,4.4,1.2


In [137]:
df.loc[2,"petal_length"]

np.float64(4.3)

In [138]:
df.iloc[1,3]  ## Last index is excluded

np.float64(1.4)

In [139]:
df.iloc[1:3,1:3]

,sepal_length,sepal_width
1,4.9,3.0
2,6.2,2.9


In [140]:
# df["sepal_length"][1] = 20
df.iloc[3,1] = np.nan
df.iloc[0,3] = np.nan
df.iloc[0,0] = 0.0

In [141]:
df.isna().sum()

Unnamed: 0      0
sepal_length    1
sepal_width     0
petal_length    1
petal_width     0
species         0
dtype: int64

In [142]:
df.fillna(20,inplace=True)

In [143]:
df.isna().sum()

Unnamed: 0      0
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [144]:
df.rename(columns={"Unnamed: 0":"serial no."},inplace=True)

In [145]:
df

,serial no.,sepal_length,sepal_width,petal_length,petal_width,species
0,0,5.1,3.5,20.0,0.2,setosa
1,1,4.9,3.0,1.4,0.2,setosa
2,2,6.2,2.9,4.3,1.3,versicolor
3,3,20.0,3.0,4.2,1.5,versicolor
4,4,6.7,3.1,5.6,2.4,virginica
5,5,6.5,3.0,5.8,2.2,virginica
6,6,5.0,3.4,1.5,0.2,setosa
7,7,6.0,2.7,5.1,1.6,versicolor
8,8,6.9,3.2,5.7,2.3,virginica
9,9,5.5,2.6,4.4,1.2,versicolor


In [146]:
df.drop(columns=["serial no."],inplace=True)

In [147]:
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,20.0,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,6.2,2.9,4.3,1.3,versicolor
3,20.0,3.0,4.2,1.5,versicolor
4,6.7,3.1,5.6,2.4,virginica
5,6.5,3.0,5.8,2.2,virginica
6,5.0,3.4,1.5,0.2,setosa
7,6.0,2.7,5.1,1.6,versicolor
8,6.9,3.2,5.7,2.3,virginica
9,5.5,2.6,4.4,1.2,versicolor


In [148]:
def add2(x):
    return x+2

df["sepal_length"] = df["sepal_length"].apply(add2)



In [149]:
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,7.1,3.5,20.0,0.2,setosa
1,6.9,3.0,1.4,0.2,setosa
2,8.2,2.9,4.3,1.3,versicolor
3,22.0,3.0,4.2,1.5,versicolor
4,8.7,3.1,5.6,2.4,virginica
5,8.5,3.0,5.8,2.2,virginica
6,7.0,3.4,1.5,0.2,setosa
7,8.0,2.7,5.1,1.6,versicolor
8,8.9,3.2,5.7,2.3,virginica
9,7.5,2.6,4.4,1.2,versicolor


In [150]:
df["sepal_length"] = df["sepal_length"].astype("int64")

In [151]:
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,7,3.5,20.0,0.2,setosa
1,6,3.0,1.4,0.2,setosa
2,8,2.9,4.3,1.3,versicolor
3,22,3.0,4.2,1.5,versicolor
4,8,3.1,5.6,2.4,virginica


In [155]:
df2 = pd.concat([df["sepal_length"],df["sepal_width"]],axis=1)

In [156]:
df2

,sepal_length,sepal_width
0,7,3.5
1,6,3.0
2,8,2.9
3,22,3.0
4,8,3.1
5,8,3.0
6,7,3.4
7,8,2.7
8,8,3.2
9,7,2.6


In [162]:
print(df.sort_values("sepal_length",inplace=True))

None


In [163]:
df

,sepal_length,sepal_width,petal_length,petal_width,species
1,6,3.0,1.4,0.2,setosa
10,6,3.2,1.3,0.2,setosa
16,6,3.4,1.6,0.2,setosa
6,7,3.4,1.5,0.2,setosa
13,7,2.9,3.6,1.3,versicolor
11,7,3.7,1.5,0.2,setosa
9,7,2.6,4.4,1.2,versicolor
0,7,3.5,20.0,0.2,setosa
17,7,2.8,4.5,1.3,versicolor
7,8,2.7,5.1,1.6,versicolor
